### ISSUE TITLE
Exec command with curl fails after updating docker version to 5.0.1 from 5.0.0

### ISSUE THREAD

**Issue by ashishvaishno** [docker/docker-py#2887]
Hello,

I just updated the docker package from 5.0.0 to 5.0.1 and since then the below command doesn't work for me 

```
response = client.containers.get(container_name).exec_run(
        '/usr/bin/curl --write-out %{http_code} --silent --output /dev/null localhost:8080/index.html',
        stderr=True, stdout=True)
```

I get the below error 
```
TypeError: __init__() got an unexpected keyword argument 'disable_buffering'
```

**Comment by felixfontein** [comment]
Duplicate of #2885.
