### ISSUE TITLE
urllib3 version conflict

### ISSUE THREAD

**Issue by oxtopus** [docker/docker-py#1526]
`ssladapter.py` makes an attempt to import `urllib3` from `requests` and if it fails, attempts to import `urllib3` directly -- see https://github.com/docker/docker-py/blob/453964466741a1c85fc420c8b40fb5710f40b017/docker/transport/ssladapter.py#L10-L13.  This may result in an older version of `urllib3` being used at runtime.  For example, the line at https://github.com/docker/docker-py/blob/453964466741a1c85fc420c8b40fb5710f40b017/docker/transport/ssladapter.py#L22 fails for versions of `urllib3` before version 1.8 with the following exception:

```
AttributeError: 'module' object has no attribute 'connection'
```

Proposal for resolution: Specify `urllib3>=1.8` in `requirements.txt` and `setup.py`, import directly from `urllib3` rather than import from the version bundled w/ `requests`.

**Comment by aaossa** [comment]
Why does importing urllib3 from requests fails? Finding out this would avoid adding a dependency

**Comment by oxtopus** [comment]
@aaosssa Ubuntu 14.04 LTS has outdated apt packages for both requests (2.2.1) and urllib3 (1.7.1).  In my case, I was using salt to configure an instance and the docker salt formula attempts to install `docker-py`.

In the following line, the `requests` import fails, resulting in an attempt to import `urllib3` directly.  

```python
try:
    import requests.packages.urllib3 as urllib3
except ImportError:
    import urllib3
```

Then, the following line fails because it successfully imported older version of `urllib3`.

```python
urllib3.connection.match_hostname = match_hostname
```

I see your point re: avoiding adding dependency, but there is an attempt to import `urllib3` directly, and the way it's being used only works with versions 1.8 or greater.  As long as there is a `import urllib3` statement, a version should be specified.

Another reasonable approach (IMHO) is to not attempt to gracefully recover from the failed import and just let it fail.  That would also avoid adding a dependency.

**Comment by oxtopus** [comment]
It's also possible that the `requests` import passes, but for the reasons I described, it's outdated and results in the same failure.

**Comment by aaossa** [comment]
Yes, but `urllib3` has been a package from `requests` for a long time, so having just:

```python
import requests.packages.urllib3 as urllib3

**Comment by shin-** [comment]
This honestly is an issue with Ubuntu and its stubbornness with messing with the packaging / bundling of certain Python libraries.

I won't add `urllib3` to our `requirements.txt` because `urllib3` is not a requirement of the docker SDK - `requests` is.

If you decide (or your OS decides) to use older versions of libraries than the ones we indicate and test our software with, you have to accept the consequences of those choices and the extra work it might entail. We have made reasonable concessions to support a wide range of setups (i.e. fallback on `urllib3` import when `requests.packages.urllib3` is unfortunately absent), but none that would compromise the quality of the software for the majority of users.

You may solve this issue by using `virtualenv`, or using a more recent version of Ubuntu.

**Comment by oxtopus** [comment]
Thanks for looking into this and I appreciate the consideration.  I understand it's a bit of a corner case, but the reason I brought it up is wrapping the `requests` import in a `try...except ImportError` block produces a bit of a red herring, resulting in some unnecessary confusion.

In my case, I'm not using `docker-py`, but the official docker formula attempts to install it by default.  At the very least, this suggestion is informed by the maxim (Explicit is better than implicit)[https://www.python.org/dev/peps/pep-0020/].
