### ISSUE TITLE
Port does not work with 0.6.5

### ISSUE THREAD

**Issue by ureyes84** [docker/docker-py#74]
I just upgraded to  `docker-py==0.2.2` and docker 0.6.5.  Also, I'm using the API version 1.4.

`port` was working fine for me but after upgrading it does not seem to work anymore. 

Here is the error I am getting:

```
    return self.docker_client.port(container, self.ide_private_port)
  File "/home/ulises/.virtualenvs/dev/local/lib/python2.7/site-packages/docker/client.py", line 381, in port
    if s_port in json_['NetworkSettings']['PortMapping']['Udp']:
TypeError: 'NoneType' object has no attribute '__getitem__'
```

I'm using `EXPOSE 8787` in my Dockerfile and I'm expecting it to map to random port in the host. This is `json_`'s value:

```
{u'SysInitPath': u'/usr/bin/docker', u'HostsPath': u'/var/lib/docker/containers/654a73a6fd22b6b534534a3c4919b49f406cfd216d5fe5079c66e69534046278/hosts', u'Created': u'2013-10-31T14:11:56.317615965-04:00', u'Image': u'8f4a20d3fe1ff24a58acf7c89506a65712f22a53df24547c25310e6228e11312', u'Args': [u'start_rstudio.sh'], u'VolumesRW': {}, u'State': {u'Ghost': False, u'Pid': 9459, u'Running': True, u'FinishedAt': u'0001-01-01T00:00:00Z', u'StartedAt': u'2013-10-31T14:11:56.363551522-04:00', u'ExitCode': 0}, u'ResolvConfPath': u'/var/lib/docker/containers/654a73a6fd22b6b534534a3c4919b49f406cfd216d5fe5079c66e69534046278/resolv.conf', u'Volumes': {}, u'Path': u'/bin/bash', u'HostnamePath': u'/var/lib/docker/containers/654a73a6fd22b6b534534a3c4919b49f406cfd216d5fe5079c66e69534046278/hostname', u'Config': {u'Env': [u'HOME=/', u'PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'], u'Hostname': u'654a73a6fd22', u'Dns': None, u'Entrypoint': [u'/bin/bash', u'start_rstudio.sh'], u'PortSpecs': None, u'Memory': 0, u'Privileged': False, u'OpenStdin': False, u'User': u'', u'AttachStderr': True, u'AttachStdout': True, u'NetworkDisabled': False, u'StdinOnce': False, u'Cmd': [], u'WorkingDir': u'', u'AttachStdin': False, u'Volumes': None, u'MemorySwap': 0, u'VolumesFrom': u'', u'Tty': False, u'CpuShares': 0, u'Domainname': u'', u'Image': u'8f4a20d3fe1f', u'ExposedPorts': {u'8787/tcp': {}}}, u'ID': u'654a73a6fd22b6b534534a3c4919b49f406cfd216d5fe5079c66e69534046278', u'NetworkSettings': {u'Bridge': u'docker0', u'PortMapping': None, u'Gateway': u'172.17.42.1', u'IPPrefixLen': 16, u'IPAddress': u'172.17.0.19', u'Ports': {u'8787/tcp': None}}, u'Name': u'/green_whale4'}
```

**Note:** I'm not using sudo since I've added my account to the `docker` group

Here is what `docker ps` returns for the container, notice the PORTS column

```
ID                  IMAGE                                         COMMAND                CREATED             STATUS              PORTS               NAMES
627ed729affe        name-527292a9637aba40d68bd75f:latest   /bin/bash start_rstu   19 seconds ago      Up 18 seconds       8787/tcp            orange_pig6         
```

How can I expose that 8787 port?

PS: Thank you very much for this wonderful project. It's been a lot of fun (and useful) working with docker and this API. Thanks!
