### ISSUE TITLE
pip 10 build failure

### ISSUE THREAD

**Issue by FRidh** [docker/docker-py#1993]
This package (3.2.1 and master) fails to build with pip 10.0.0:

```
File "setup.py", line 12, in <module>
    if 'docker-py' in [x.project_name for x in pip.get_installed_distributions()]:
AttributeError: 'module' object has no attribute 'get_installed_distributions'
```

The function `get_installed_distributions` is now part of `pip._internal`.

**Comment by FRidh** [comment]
Note this in effect breaks moto and thereby the testing of pandas.

**Comment by FRidh** [comment]
No, it was not.

https://github.com/pypa/pip/issues/5154#issuecomment-378197307

Although by not prefixing it with an underscore it never was that obvious. Until now then.

**Comment by FRidh** [comment]
Probably `pkg_resources.working_set` is best used here.

**Comment by adamtheturtle** [comment]
https://github.com/docker/docker-py/commit/1d6f8ecf9277ef1c77f3d530efaafd39323cc8e7#diff-2eeaed663bd0d25b7e608891384b7298 fixes this issue but is not yet released.

**Comment by FRidh** [comment]
Though not mentioned in PR or commit, a fix was merged as part of https://github.com/docker/docker-py/pull/1990.

@shin- can we get a 3.2.2?
